### ISSUE TITLE
do you guys have any good ideas or resources on the pop up book making?

### ISSUE THREAD

**Issue by renning890726** [taiyang777/scottishpeople#1]

**Comment by wenqicai1** [comment]
https://www.youtube.com/watch?v=prfPIIcENNY

**Comment by taiyang777** [comment]
This is a youtube video, which could be helpful and give us some inspirations. https://www.youtube.com/watch?v=F1zo5zh8k1k

**Comment by wenqicai1** [comment]
https://www.youtube.com/watch?v=nGPIOz1QMEo

**Comment by renning890726** [comment]
http://v.youku.com/v_show/id_XNzkwNjczNDIw.html?f=22006270

**Comment by renning890726** [comment]
https://zhuanlan.zhihu.com/p/30937433

**Comment by taiyang777** [comment]
https://www.youtube.com/watch?v=tjUSei_6XUU
https://www.youtube.com/watch?v=E037yUPgzPY

**Comment by taiyang777** [comment]
This is what I need to do tomorrow, it looks cool: https://www.youtube.com/watch?v=kWXnkc28Bnw
